### PR TITLE
Add the ability to publish CLI with workflow_dispatch

### PR DESCRIPTION
**Pull request by ono-max**
I confirmed this works in https://github.com/ono-max/vscode-launchable/commit/37519472ad111fc22e8eeb12527e24bca612c19a.

### CODE REVIEW

**Comment by Konboi** [comment]
In my understanding `'workflow_dispatch'` is for manual execution.
Why do you need this if statement??

**Comment by ono-max** [comment]
There are two reasons.

1. Since setting for tagpr is wrong, I need to release https://github.com/launchableinc/cli/releases/tag/v1.71.0 manually now.
2. tagpr might be broken if Github is not stable. We'll need to publish it manually in this case.

**Review by Konboi — APPROVED** [review]
> Since setting for tagpr is wrong, I need to release https://github.com/launchableinc/cli/releases/tag/v1.71.0 manually now.

I got it

**Comment by ono-max** [comment]
Thank you!

**Pull request merged**
