### PR TITLE
Fix/quotations

### PR DESCRIPTION
**Pull request by shibuiwilliam**
# What
- Fix single quote to double quote where possible to integrate usage of quotation through codebase.
- This is just refactoring, and no need to hurry.

### CODE REVIEW

**Comment by Konboi** [comment]
By the way, where is the mentioned that we should use a double quote instead of a single quote?

**Review by Konboi — APPROVED** [review]
LGTM but …
I want to keep the git history without these changes for easy to access past contexts, especially for the `git blame`
Do you have any good ideas?

**Comment by shibuiwilliam** [comment]
> LGTM but … I want to keep the git history without these changes for easy to access past contexts, especially for the `git blame` Do you have any good ideas?

Oh, ok. I close this PR without merging.
I just aimed to organize the code to use the same quotation rather than mixing them.

**Comment by Konboi** [comment]
@shibuiwilliam How about adding `.git-blame-ignore-revs` same time?  It seems to be that we can ignore these commit.

**Pull request closed without merging**
