### PR TITLE
Fix Bazel plugin

### PR DESCRIPTION
**Pull request by ninjinkun**
Removed `//` from package props in Bazel plugin. Also added missing Bazel plugin unit tests at `tests/test_runners/test_bazel.py`.

### CODE REVIEW

**Review by shuheiktgw — APPROVED** [review]
👍  

Can you release a new one and contact our customer?

**Comment by shuheiktgw** [comment]
Whoops, the CI seems to fail

**Comment by ninjinkun** [comment]
@shuheiktgw I'm fixing the failure. Let me see…

**Comment by ninjinkun** [comment]
@shuheiktgw Fixed!

**Comment by ninjinkun** [comment]
Okay. I'm going to release it and contact the customer.

**Pull request merged**
