### PR TITLE
rm bracket

### PR DESCRIPTION
**Pull request by Konboi**
SSIA

### CODE REVIEW

**Comment by ninjinkun** [comment]
@Konboi I also proposed to add a slash like `TestRunner/gradle` at the Slack post.

**Comment by Konboi** [comment]
@ninjinkun I fixed. Could you review again?

**Review by ninjinkun — APPROVED** [review]
LGTM!

**Comment by awilkes** [comment]
Do we need to do anything special for 'custom' profiles? We could end up with a conflict if a customer named their profile the same as one of ours (unlikely, but you never know)

Perhaps `TestRunner#gradle` for standard ones and `TestRunner#{org}/{ws}/{name}` for custom? Just an idea...

**Comment by Konboi** [comment]
I think don't need it.
We should protect not to register custom plugins as general plugin names than change UA names.

What do you think?

**Comment by awilkes** [comment]
Sounds good! Good idea.

**Pull request merged**
