### PR TITLE
Updated test path

### PR DESCRIPTION
**Pull request by kohsuke**
According to Al, the structure we want is file > class > testcase
whereas the code produced file > testcase > class

### CODE REVIEW

**Comment by kohsuke** [comment]
Kinda odd that no tests fail as a result of this change...

**Review by awilkes — APPROVED** [review]
Looks good to me!

However, I do wonder why the original approach was chosen versus this approach. 🤔 Especially since it appears somewhat intentional.

**Comment by kohsuke** [comment]
Turns out tests were too lax to catch this problem. Tightened it up to be sensitive to the order of test paths.

**Comment by kohsuke** [comment]
@yoshiori Upon further analysis I think something is off, unrelated to this change. I need you to chime in.

Looking at `pytest/record_test_result.json`, I see that it's producing "class -> testcase" test paths. `pytest/subset_result.json` is expecting `file -> testcase -> class` test paths prior to this change. This change made it `file -> class -> testcase`. Neither of those match up.

Test paths need to be aligned, meaning paths used in subsetting must be ancestors of paths used in collecting reports.

**Comment by yoshiori** [comment]
@kohsuke that was test data against the old specification. In the old days, the `file field` did not exist. I forgot to update it.

**Review by yoshiori — APPROVED** [review]

**Comment by awilkes** [comment]
Sweet, thanks @yoshiori and @kohsuke!

I checked this out locally and confirmed that it works:

```bash
awilkes@almac ~/code/launchable/cli
> $ pytest --collect-only -q ../intro-to-pytest/ | python3 -m launchable subset --build FOO --confidence 100% pytest > subset.txt
Your model is currently in training
Launchable created subset 57381 for build FOO (test session 434088) in workspace launchableinc/awilkes

|           |   Candidates |   Estimated duration (%) |   Estimated duration (min) |
|-----------|--------------|--------------------------|----------------------------|
| Subset    |            1 |                 0.917431 |                1.66667e-05 |
| Remainder |          108 |                99.0826   |                0.0018      |
|           |              |                          |                            |
| Total     |          109 |               100        |                0.00181667  |

Run `launchable inspect subset --subset-id 57381` to view full subset details
                                                                                                                                                                
awilkes@almac ~/code/launchable/cli
> $ launchable inspect subset --subset-id 57381
|   Order | Test Path                                                                                                                                                            | In Subset   |   Estimated duration (sec) |
|---------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------|----------------------------|
|       1 | file=intro-to-pytest/tests/16_scoped_and_meta_fixtures_test.py#class=intro-to-pytest.tests.16_scoped_and_meta_fixtures_test#testcase=test_scoped_fixtures[10]        | ✔           |                      0.001 |
```

I am going to merge this and release a new version.

**Pull request merged**
