### PR TITLE
update readme; add installation

### PR DESCRIPTION
**Pull request by shibuiwilliam**
# What
- add installation in readme

### CODE REVIEW

**Comment by Konboi** [comment]
I think we don't need to add this. Because this part already exists https://docs.launchableinc.com/getting-started.
We should keep README.md for developers, I think.
How about you??

**Review by draftcode — APPROVED** [review]

**Comment by draftcode** [comment]
I'm ok with having both. Both anyway have the same content, right?

**Comment by shibuiwilliam** [comment]
My point is to add `python setup.py install` to help a developer to install it with local changes.
It is true that users read the [docs](https://docs.launchableinc.com/getting-started) and that should be the main document rather than the github readme.

**Comment by yoshiori** [comment]
[Off topic]
`pip3 install --editable .` 
I often forget to do this, so I should probably write this down somewhere, too.

**Comment by shibuiwilliam** [comment]
> pip3 install --editable .

True, this is fine as well. I'm just use to run `python setup.py install`.
`pip3 install git+git@github.com:launchableinc/cli.git@${COMMIT_HASH}` may be fine as well.

**Comment by Konboi** [comment]
> My point is to add python setup.py install to help a developer to install it with local changes.

I see, LGTM

**Pull request merged**
