### PR TITLE
Add optimize test command

### PR DESCRIPTION
**Pull request by ninjinkun**
Add `launchable optimize test` command. This PR should merge after https://github.com/launchableinc/cli/pull/52.

### How to use
```shell
$ LAUNCHABLE_TEST_SESSION=$(launchable record session --name 123)             
$ rails test $(launchable optimize test $(find test -regex .*_test.rb | tr "\n" " ") --name 123 --session $LAUNCHABLE_TEST_SESSION)
```

### CODE REVIEW

**Comment by ninjinkun** [comment]
I haven't succeeded in this run yet because my local API caused 500. I'll try it again tommorw.

**Comment by shuheiktgw** [comment]
@ninjinkun Did you hit the subsetting endpoint locally then it returned 500? I think I know why that happened so I'm happy to explain it if you need 👍

**Comment by ninjinkun** [comment]
@shuheiktgw I succeeded to run it! Please review this PR.

**Review by shuheiktgw — APPROVED** [review]
👍

**Pull request merged**
