### PR TITLE
Post to Slack channel when docs change

### PR DESCRIPTION
**Pull request by kohsuke**
We should be all aware of what's changing the doc

### CODE REVIEW

**Comment by kohsuke** [comment]
The change currently goes to the CSM channel.

**Comment by awilkes** [comment]
Great idea!

**Comment by awilkes** [comment]
Hm, docs updates that come from Gitbook don't come through as pull requests. Can we watch for changed files on the main branch instead?

**Comment by kohsuke** [comment]
Good catch. Fixed.

**Review by takanabe — APPROVED** [review]

**Pull request merged**
